[package]
name = "fork_union"
description = "OpenMP-style cross-platform fine-grained parallelism library"
version = "0.3.3"
edition = "2021"
authors = ["Ash Vardanian"]
license = "Apache-2.0"
repository = "https://github.com/ashvardanian/fork_union"

[lib]
path = "fork_union.rs"
